name: Publish Layer Exporter

on:
  push:
    branches: [ "plugin/layer-exporter" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: plugin/layer-exporter.
      - name: publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:airslice/reearth-plugin-layer-exporter.git
          BRANCH: main
          FOLDER: dist/plugin
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_LAYER_EXPORTER }}
