name: Publish Pedestrian

on:
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: plugin/pedestrian
      - name: publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:airslice/reearth-plugin-pedestrian.git
          BRANCH: main
          FOLDER: dist/plugin
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PEDESTRIAN }}
